language: python


branches:
 only: master

script:
 - ./build.sh
 # - git add tag

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
