name: blog build
on: 
  push:
    branches:
        - master
  schedule:
     - cron: '00 07 * * *'
    

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: ./build.sh

      - name: GIT commit and push all changed files
        env: 
            CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
            CI_COMMIT_AUTHOR: Continuous Integration
        run: |
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "username@users.noreply.github.com"
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push


